### ISSUE TITLE
Training Error. AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Zeit42** [csvance/keras-mobile-detectnet#4]
I'm trying to train and I used this command:

`python3 train.py --batch-size 24 --epochs 500 --train-path ~/my/folder/train --eval-path ~/my/folder/val --workers 4`

but I get the following error:

```
File "/home/angelo/keras-mobile-detectnet/generator.py", line 99, in __getitem__
old_shape = image.shape
AttributeError: 'NoneType' object has no attribute 'shape'

```
How do I get around this?

**Comment by csvance** [comment]
Copying my reply from nVidia Devtalk:

Usually this indicates an issue with the path to images. Could also be a non image file present in the directory (like thumbs.db or .DS_Store for instance)

How is your directory structure for your training data? It should match the KITTI format: https://github.com/NVIDIA/DIGITS/tree/master/digits/extensions/data/objectDetection


--train-path and --val-path should point to the directory which contains both an images and labels directory.

**Comment by Zeit42** [comment]
In our case, there were hidden files. 

For anyone that encounters the same issue, just go to the directory, and then hit Ctrl+H, sort the files by name and delete everything with '._'.
